services:
  app:
    build: .
    image: my-spring-app
    container_name: spring-container
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      antmedia:
        condition: service_healthy


  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    container_name: janus-gateway
    command: [ "/usr/local/bin/janus", "-F", "/usr/local/etc/janus" ]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8001:8001"
      - "7088:7088"
      - "7089:7089"
    restart: always

  antmedia:
    image: 'boris1993/ant-media-server:latest'
    container_name: antmedia
    ports:
      - "1935:1935"       # RTMP
      - "5080:5080"       # HTTP
      - "5443:5443"       # HTTPS
      - "3478:3478/udp"   # TURN/STUN (WebRTC)
    volumes:
      - antmedia:/usr/local/antmedia/
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://antmedia:5080/LiveApp" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  antmedia: